import merge from 'lodash-es/merge';
import type { Colors, Theme } from './types';
import defaultTheme from './default';

export const colors: Colors = {
  white: '#FFFFFF',
  black: '#404c56',
  red: '#F45B69',
  orange: '#FC7753',
  yellow: '#FBD97A',
  green: '#59C3C3',
  blue: '#4062BB',
  violet: '#52489C',
  whites: ['#9b9b9b', '#cccccc', '#ffffff', '#ffffff', '#ffffff'],
  blacks: ['#000000', '#232323', '#404c56', '#457ca0', '#7eaff0'],
  reds: ['#5f262a', '#a64048', '#f45b69', '#ff768c', '#ff94b0'],
  oranges: ['#6b3728', '#b1563d', '#fc7753', '#ff996a', '#ffb880'],
  yellows: ['#857a62', '#bfa86f', '#fbd97a', '#ffff84', '#ffff8c'],
  greens: ['#575757', '#658a8a', '#59c3c3', '#63feff', '#a2ffff'],
  blues: ['#0e152c', '#26396f', '#4062bb', '#608eff', '#a6bdff'],
  violets: ['#040019', '#2a2456', '#52489c', '#7e6fe9', '#ac99ff'],
  background: '#222831',
  primary: 'hsl(237, 100%, 86%)',
  secondary: 'hsl(211, 97%, 86%)',
  tertiary: 'hsl(169, 100%, 83%)',
  quatenary: 'hsl(278, 93%, 84%)',
  emphasis: '#8ef6e4',
  subtle: '#f3f3f3',
  alert: 'hsl(350, 100%, 77%)',
  fonts: {
    primary: '#FFFFFF',
    secondary: '#EEE',
    inverse: '#404c56',
  },
};

const darkTheme = {
  name: 'dark',
  colors,
  button: {
    primary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff0ff',
        borderColor: '#fff0ff',
      },
      backgroundColor: '#defcf9',
      borderColor: '#defcf9',
      color: 'black',
    },
    secondary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#cadefc',
      borderColor: '#cadefc',
      color: 'black',
    },
    tertiary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#c8c3ff',
        borderColor: '#c8c3ff',
      },
      backgroundColor: '#c3bef0',
      borderColor: '#c3bef0',
      color: 'black',
    },
    quatenary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      color: 'black',
    },
    alert: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: 'alert(350, 100%, 84%)',
        borderColor: 'alert(350, 100%, 84%)',
      },
      backgroundColor: 'alert',
      borderColor: 'alert',
      color: 'black',
    },
    primaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff0ff',
        borderColor: '#fff0ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: 'black',
    },
    secondaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: 'black',
    },
    tertiaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ffefff',
        borderColor: '#ffefff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: 'black',
    },
    quatenaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#cca8e9',
    },
    alertInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ffefff',
        borderColor: '#ffefff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: 'alert',
    },
  },
};

const theme: Theme = merge({}, defaultTheme, darkTheme);

export default theme;
