import type { Colors } from './types';

export const colors: Colors = {
  white: '#FFFFFF',
  black: '#232323',
  red: '#F45B69',
  orange: '#FC7753',
  yellow: '#FBD97A',
  green: '#59C3C3',
  blue: '#4062BB',
  violet: '#52489C',
  whites: ['#9b9b9b', '#cccccc', '#ffffff', '#ffffff', '#ffffff'],
  blacks: ['#000000', '#232323', '#404c56', '#457ca0', '#7eaff0'],
  reds: ['#5f262a', '#a64048', '#f45b69', '#ff768c', '#ff94b0'],
  oranges: ['#6b3728', '#b1563d', '#fc7753', '#ff996a', '#ffb880'],
  yellows: ['#857a62', '#bfa86f', '#fbd97a', '#ffff84', '#ffff8c'],
  greens: ['#575757', '#658a8a', '#59c3c3', '#63feff', '#a2ffff'],
  blues: ['#0e152c', '#26396f', '#4062bb', '#608eff', '#a6bdff'],
  violets: ['#040019', '#2a2456', '#52489c', '#7e6fe9', '#ac99ff'],
  background: 'rgb(246,246,246)',
  primary: '#0C0C0C',
  secondary: '#EF3F47',
  tertiary: '#59C3C3',
  quatenary: '#FC7753',
  emphasis: '#E28413',
  subtle: '#DADAD9',
  alert: '#F45B69',
  fonts: {
    primary: '#232323',
    secondary: '#404c56',
    inverse: '#FFFFFF',
  },
};

const textStyles = {
  uppercase: {
    textTransform: 'uppercase',
  },
  label: {
    textTransform: 'uppercase',
  },
  caption: {
    textTransform: 'uppercase',
  },
};

const fonts = {
  heading: `"Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;`,
  subheading: `"Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;`,
  body: `"Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif`,
};

const fontWeights = [100, 200, 300, 400, 500, 600, 700, 800];

const lightTheme = {
  name: 'light',
  breakpoints: ['60rem', '90rem', '120rem', '180rem'],
  space: [
    0,
    '0.4rem',
    '0.8rem',
    '1.6rem',
    '3.2rem',
    '6.4rem',
    '8.8rem',
    '12.8rem',
    '25.6rem',
    '51.2rem',
  ],
  radii: [0, '0.2rem', '0.4rem', '0.8rem', '1.6rem', '3.2rem', '6.4rem'],
  sizes: [
    '0rem',
    '12rem',
    '24rem',
    '36rem',
    '48rem',
    '60rem',
    '72rem',
    '84rem',
    '96rem',
    '108rem',
    '120rem',
  ],
  colors,
  fonts,
  fontSizes: [
    '1.2rem',
    '1.6rem',
    '1.8rem',
    '2.4rem',
    '3.2rem',
    '4rem',
    '4.8rem',
    '6rem',
  ],
  textStyles,
  fontWeights,
  lineHeights: [0.84, 1, 1.2, 1.6, 2],
  letterSpacings: ['-0.8px', '0.2px', '1.2px', '3px'],
  borders: [],
  borderWidths: [],
  borderStyles: [],
  shadows: ['0px 12px 40px 0px rgba(0,0,0,0.2)'],
  // zIndices: range(0, 2000, 10),
  perspectives: [0, 300, 600, 900, 1200],
  transforms: {
    none: 'none',
    back: 'translate3d(0, 0, -100px)',
  },
  transitions: {
    none: 'none',
    allEaseInOutSlow: 'all 600ms ease-in-out',
    allEaseInOut: 'all 240ms ease-in-out',
    allEaseInOutFast: 'all 160ms ease-in-out',
  },
  transformOrigins: {
    topLeft: '0 0',
    topCenter: '50% 0',
    topRight: '100% 0',
    bottomLeft: '0 100%',
    bottomCenter: '50% 100%',
    bottomRight: '100% 100%',
    centerLeft: '0% 50%',
    centerRight: '100% 50%',
    center: '50% 50%',
  },
  spinner: {
    size: '6rem',
  },
  button: {
    primary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#592e3c',
        borderColor: '#592e3c',
      },
      backgroundColor: '#0C0C0C',
      borderColor: '#0C0C0C',
      color: '#FFFFFF',
    },
    secondary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ff6468',
        borderColor: '#ff6468',
      },
      backgroundColor: '#EF3F47',
      borderColor: '#EF3F47',
      color: '#FFFFFF',
    },
    tertiary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#00d7d9',
        borderColor: '#00d7d9',
      },
      backgroundColor: '#59C3C3',
      borderColor: '#59C3C3',
      color: '#FFFFFF',
    },
    quatenary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      color: '#FFFFFF',
    },
    alert: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ff627c',
        borderColor: '#ff627c',
      },
      backgroundColor: '#F45B69',
      borderColor: '#F45B69',
      color: '#FFFFFF',
    },
    primaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff0ff',
        borderColor: '#fff0ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#0C0C0C',
    },
    secondaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#F45B69',
    },
    tertiaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ffefff',
        borderColor: '#ffefff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#59C3C3',
    },
    quatenaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#FC7753',
    },
    alertInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ffefff',
        borderColor: '#ffefff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#F45B69',
    },
    clear: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      borderWidth: 0,
      hover: {
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
    },
  },
  nav: {
    default: {
      padding: [2, 3, 3],
      transition: 'all 320ms ease-in-out',
    },
    sticky: {
      padding: [2, 3, 3],
      position: 'sticky',
      top: 0,
      transition: 'all 320ms ease-in-out',
    },
    clear: {
      padding: [2, 3, 3],
      position: 'sticky',
      top: 0,
      backgroundColor: 'transparent',
      color: 'white',
      transition: 'all 320ms ease-in-out',
    },
  },
  text: {
    link: {
      textDecoration: 'none',
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'inherit',
      fontWeight: 'inherit',
      lineHeight: 'inherit',
      fontSize: 'inherit',
    },
    navLink: {
      fontSize: [4, 2],
      lineHeight: [3, 2],
      letterSpacing: [1],
      color: '#404040',
    },
    footerLink: {
      fontSize: [2],
      lineHeight: [2],
      letterSpacing: [1],
      color: '#404040',
    },
    p: {
      fontFamily: fonts.body,
      fontSize: [2],
      fontWeight: [3],
      color: 'fonts.secondary',
    },
    h1: {
      fontFamily: fonts.heading,
      fontSize: [6, 7, 7],
      fontWeight: [3],
      lineHeight: [1, 2, 2],
      color: 'fonts.primary',
    },
    h2: {
      fontFamily: fonts.heading,
      fontSize: [5, 6, 6],
      lineHeight: [1, 2, 2],
      fontWeight: [3],
      color: 'fonts.secondary',
    },
    h3: {
      fontFamily: fonts.heading,
      fontSize: [3, 4],
      lineHeight: [1, 2, 2],
      fontWeight: [2],
      color: 'fonts.primary',
    },
    h4: {
      fontFamily: fonts.subheading,
      fontSize: [3, 4, 4],
      lineHeight: [1, 2, 2],
      fontWeight: [3],
      color: 'fonts.primary',
    },
    h5: {
      fontFamily: fonts.subheading,
      fontSize: [2, 3, 3],
      lineHeight: [1, 2, 2],
      fontWeight: [3],
      color: 'fonts.primary',
    },
    h6: {
      fontFamily: fonts.subheading,
      fontSize: [1, 2, 2],
      lineHeight: [1, 2, 2],
      fontWeight: [3],
      color: 'fonts.secondary',
    },
    span: {
      fontFamily: 'inherit',
      fontSize: 'inherit',
      color: 'fonts.secondary',
    },
    label: {
      fontFamily: fonts.body,
      fontSize: [1, 2, 2],
      lineHeight: [1, 2, 2],
      color: 'fonts.secondary',
    },
    input: {
      fontFamily: fonts.body,
      fontSize: [1, 2, 2],
      lineHeight: [1, 2, 2],
      color: 'fonts.secondary',
    },
    caption: {
      fontFamily: fonts.body,
      fontSize: [0, 1, 1],
      lineHeight: [1, 2, 2],
      color: 'fonts.secondary',
    },
  },
  form: {
    default: {
      width: '100%',
    },
  },
  box: {
    default: {
      bg: 'transparent',
      borderWidth: 0,
      borderStyle: 'solid',
      borderColor: 'primary',
    },
    card: {
      bg: 'white',
      borderWidth: 0,
      borderRadius: 3,
      transition: 'all 340ms ease-in-out',
    },
  },
  container: {
    default: {
      width: '100%',
      margin: '0 auto',
    },
    main: {
      width: '100%',
      margin: 'auto',
      maxWidth: 10,
      px: [3, 2, 0],
      paddingBottom: [3],
    },
    nav: {
      width: '100%',
      margin: 'auto',
      maxWidth: 10,
      p: 0,
    },
  },
  icon: {
    primary: {
      stroke: 'transparent',
      fill: colors.primary,
    },
    secondary: {
      stroke: 'transparent',
      fill: colors.secondary,
    },
    tertiary: {
      stroke: 'transparent',
      fill: colors.tertiary,
    },
    quaternary: {
      stroke: 'transparent',
      fill: colors.quaternary,
    },
    white: {
      stroke: 'transparent',
      fill: colors.white,
    },
    black: {
      stroke: 'transparent',
      fill: colors.black,
    },
  },
  input: {
    default: {
      fontFamily: fonts.body,
      fontSize: [2],
      lineHeight: [1, 2],
      borderRadius: 2,
      px: [2, 2, 3],
      py: [3],
      borderColor: '#cfcfcf',
      backgroundColor: `rgba(255,255,255,0.7)`,
      minWidth: [2, 3, 4],
      borderStyle: 'solid',
      borderWidth: 1,
    },
    quantitySelector: {
      fontFamily: fonts.body,
      fontSize: [2, 3, 3],
      lineHeight: [1, 2],
      borderRadius: 1,
      px: [2],
      py: [0],
      my: [0],
      border: 'none',
      borderColor: '#cfcfcf',
      backgroundColor: `transparent`,
      minWidth: [2],
      textAlign: 'center',
    },
  },
  select: {
    default: {
      fontFamily: fonts.body,
      fontSize: [2],
      lineHeight: [3, 4],
      borderRadius: 2,
      px: [2, 3],
      py: [0],
      borderColor: '#cfcfcf',
      backgroundColor: `rgba(255,255,255,0.7)`,
      minWidth: [2, 3],
      borderStyle: 'solid',
      borderWidth: 1,
    },
  },
  break: {
    default: {
      backgroundColor: 'transparent',
      width: '100%',
      height: 0,
    },
  },
  image: {
    default: {},
  },
  video: {
    default: {},
  },
  iframe: {
    default: {
      border: 'none',
      maxWidth: '100%',
    },
  },
  table: {
    default: {
      borderColor: 'black',
      borderWidth: '1px',
      borderStyle: 'solid',
      backgroundColor: 'white',
    },
  },
};

export default lightTheme;
