import merge from 'lodash-es/merge';
import type { Colors, Theme } from './types';
import defaultTheme from './default';

export const colors: Colors = {
  white: '#FFFFFF',
  black: '#404c56',
  red: '#F45B69',
  orange: '#FC7753',
  yellow: '#FBD97A',
  green: '#59C3C3',
  blue: '#4062BB',
  violet: '#52489C',
  whites: ['#9b9b9b', '#cccccc', '#ffffff', '#ffffff', '#ffffff'],
  blacks: ['#000000', '#232323', '#404c56', '#457ca0', '#7eaff0'],
  reds: ['#5f262a', '#a64048', '#f45b69', '#ff768c', '#ff94b0'],
  oranges: ['#6b3728', '#b1563d', '#fc7753', '#ff996a', '#ffb880'],
  yellows: ['#857a62', '#bfa86f', '#fbd97a', '#ffff84', '#ffff8c'],
  greens: ['#575757', '#658a8a', '#59c3c3', '#63feff', '#a2ffff'],
  blues: ['#0e152c', '#26396f', '#4062bb', '#608eff', '#a6bdff'],
  violets: ['#040019', '#2a2456', '#52489c', '#7e6fe9', '#ac99ff'],
  background: 'rgb(246,246,246)',
  
  primary: '#2D96EB',
  secondary: '#44BBA4',
  tertiary: '#977DF7',
  quatenary: '#E8E9EB',
  emphasis: '#E28413',
  subtle: '#f6fbdc',
  alert: '#F45B69',

  fonts: {
    primary: '#232323',
    secondary: '#404c56',
    inverse: '#ffffff',
  },
};

const lightTheme = {
  name: 'light',
  colors,
  button: {
    primary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: 'hsl(207, 89%, 64%)',
        borderColor: 'hsl(207, 89%, 64%)',
      },
      backgroundColor: 'primary',
      borderColor: 'primary',
      color: '#FFFFFF',
    },
    secondary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: 'hsl(168, 52%, 55%)',
        borderColor: 'hsl(168, 52%, 55%)',
      },
      backgroundColor: 'secondary',
      borderColor: 'secondary',
      borderWidth: '2px',
      color: '#FFFFFF',
    },
    tertiary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: 'hsl(253, 93%, 78%)',
        borderColor: 'hsl(253, 93%, 78%)',
      },
      backgroundColor: 'tertiary',
      borderColor: 'tertiary',
      color: '#FFFFFF',
    },
    quatenary: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      color: '#FFFFFF',
    },
    alert: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ff627c',
        borderColor: '#ff627c',
      },
      backgroundColor: '#F45B69',
      borderColor: '#F45B69',
      color: '#FFFFFF',
    },
    primaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff0ff',
        borderColor: '#fff0ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: 'rgb(193,39,45)',
    },
    secondaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#F45B69',
    },
    tertiaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ffefff',
        borderColor: '#ffefff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#0060EE',
    },
    quatenaryInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#fff2ff',
        borderColor: '#fff2ff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#FC7753',
    },
    alertInverted: {
      borderStyle: 'solid',
      lineHeight: [2, 3],
      fontSize: [2],
      fontWeight: [4],
      borderRadius: [3],
      minWidth: [1, 1, 2],
      padding: [3],
      my: [2, 2, 3],
      transition: 'all 140ms linear',
      textTransform: 'uppercase',
      '&:hover': {
        backgroundColor: '#ffefff',
        borderColor: '#ffefff',
      },
      backgroundColor: '#FFFFFF',
      borderColor: '#FFFFFF',
      color: '#F45B69',
    },
  },
  icon: {
    primary: {
      stroke: 'transparent',
      fill: colors.primary,
    },
    secondary: {
      stroke: 'transparent',
      fill: colors.secondary,
    },
    tertiary: {
      stroke: 'transparent',
      fill: colors.tertiary,
    },
    quaternary: {
      stroke: 'transparent',
      fill: colors.quaternary,
    },
    white: {
      stroke: 'transparent',
      fill: colors.white,
    },
    black: {
      stroke: 'transparent',
      fill: colors.black,
    },
  },
};

const theme: Theme = merge({}, defaultTheme, lightTheme);

export default theme;
